server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waitingdb?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


kakao:
  api-url: https://kakaoapi.example.com/send
  access-token: YOUR_KAKAO_ACCESS_TOKEN


#jwt:
#  secret: your_jwt_secret_key
#  expiration: 3600000 # 1시간 (밀리초)
#
