server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mydb2025.c16agemciyrr.ap-northeast-2.rds.amazonaws.com:3306/capstone?serverTimezone=Asia/Seoul
    username: admin
    password: 6174812Gus!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect


coolsms:
  api-key: NCSJG6MXSTMHGOLL
  api-secret: PGWQDQZMZM7HRELYYJXE6HAXT8DE539K
  from: 01037415951


#jwt:
#  secret: your_jwt_secret_key
#  expiration: 3600000 # 1시간 (밀리초)
#
